// Mocks generated by Mockito 5.4.6 from annotations
// in flower_tracking/test/features/auth/apply_screen/data/datasources/remote/apply_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:flower_tracking/core/api_manager/api_manager.dart' as _i3;
import 'package:flower_tracking/features/auth/apply_screen/data/models/response/apply_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApplyResponseDto_0 extends _i1.SmartFake
    implements _i2.ApplyResponseDto {
  _FakeApplyResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i3.RestClient {
  MockRestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApplyResponseDto> applyDriver(
    String? country,
    String? firstName,
    String? lastName,
    String? vehicleType,
    String? vehicleNumber,
    _i5.File? vehicleLicense,
    String? email,
    String? phone,
    String? nid,
    _i5.File? nIDImg,
    String? password,
    String? rePassword,
    String? gender,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyDriver, [
              country,
              firstName,
              lastName,
              vehicleType,
              vehicleNumber,
              vehicleLicense,
              email,
              phone,
              nid,
              nIDImg,
              password,
              rePassword,
              gender,
            ]),
            returnValue: _i4.Future<_i2.ApplyResponseDto>.value(
              _FakeApplyResponseDto_0(
                this,
                Invocation.method(#applyDriver, [
                  country,
                  firstName,
                  lastName,
                  vehicleType,
                  vehicleNumber,
                  vehicleLicense,
                  email,
                  phone,
                  nid,
                  nIDImg,
                  password,
                  rePassword,
                  gender,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ApplyResponseDto>);
}
