// Mocks generated by Mockito 5.4.6 from annotations
// in flower_tracking/test/features/auth/apply_screen/data/datasources/remote/apply_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i10;

import 'package:flower_tracking/core/api_manager/api_manager.dart' as _i7;
import 'package:flower_tracking/features/auth/apply_screen/data/models/response/apply_response_dto.dart'
    as _i6;
import 'package:flower_tracking/features/auth/forget_password/data/models/forget_password_dto.dart'
    as _i2;
import 'package:flower_tracking/features/auth/forget_password/data/models/reset_password_dto.dart'
    as _i4;
import 'package:flower_tracking/features/auth/forget_password/data/models/verify_code_dto.dart'
    as _i3;
import 'package:flower_tracking/features/auth/login/data/model/request/login_request_dto.dart'
    as _i9;
import 'package:flower_tracking/features/auth/login/data/model/response/login_response_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordDto_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordDto {
  _FakeForgetPasswordDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyCodeDto_1 extends _i1.SmartFake implements _i3.VerifyCodeDto {
  _FakeVerifyCodeDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordDto_2 extends _i1.SmartFake
    implements _i4.ResetPasswordDto {
  _FakeResetPasswordDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponseDto_3 extends _i1.SmartFake
    implements _i5.LoginResponseDto {
  _FakeLoginResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyResponseDto_4 extends _i1.SmartFake
    implements _i6.ApplyResponseDto {
  _FakeApplyResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i7.RestClient {
  MockRestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.ForgetPasswordDto> forgetPassword(
    Map<String, dynamic>? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [email]),
            returnValue: _i8.Future<_i2.ForgetPasswordDto>.value(
              _FakeForgetPasswordDto_0(
                this,
                Invocation.method(#forgetPassword, [email]),
              ),
            ),
          )
          as _i8.Future<_i2.ForgetPasswordDto>);

  @override
  _i8.Future<_i3.VerifyCodeDto> verifyCode(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [body]),
            returnValue: _i8.Future<_i3.VerifyCodeDto>.value(
              _FakeVerifyCodeDto_1(
                this,
                Invocation.method(#verifyCode, [body]),
              ),
            ),
          )
          as _i8.Future<_i3.VerifyCodeDto>);

  @override
  _i8.Future<_i4.ResetPasswordDto> resetPassword(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [body]),
            returnValue: _i8.Future<_i4.ResetPasswordDto>.value(
              _FakeResetPasswordDto_2(
                this,
                Invocation.method(#resetPassword, [body]),
              ),
            ),
          )
          as _i8.Future<_i4.ResetPasswordDto>);

  @override
  _i8.Future<_i5.LoginResponseDto> login(_i9.LoginRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i5.LoginResponseDto>.value(
              _FakeLoginResponseDto_3(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.LoginResponseDto>);

  @override
  _i8.Future<_i6.ApplyResponseDto> applyDriver(
    String? country,
    String? firstName,
    String? lastName,
    String? vehicleType,
    String? vehicleNumber,
    _i10.File? vehicleLicense,
    String? email,
    String? phone,
    String? nid,
    _i10.File? nIDImg,
    String? password,
    String? rePassword,
    String? gender,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyDriver, [
              country,
              firstName,
              lastName,
              vehicleType,
              vehicleNumber,
              vehicleLicense,
              email,
              phone,
              nid,
              nIDImg,
              password,
              rePassword,
              gender,
            ]),
            returnValue: _i8.Future<_i6.ApplyResponseDto>.value(
              _FakeApplyResponseDto_4(
                this,
                Invocation.method(#applyDriver, [
                  country,
                  firstName,
                  lastName,
                  vehicleType,
                  vehicleNumber,
                  vehicleLicense,
                  email,
                  phone,
                  nid,
                  nIDImg,
                  password,
                  rePassword,
                  gender,
                ]),
              ),
            ),
          )
          as _i8.Future<_i6.ApplyResponseDto>);
}
