import 'package:dropdown_textfield/dropdown_textfield.dart';

List<DropDownValueModel> countries = [
  DropDownValueModel(name: 'Afghanistan', value: 'Afghanistan'),
  DropDownValueModel(name: 'Algeria', value: 'Algeria'),
  DropDownValueModel(name: 'Argentina', value: 'Argentina'),
  DropDownValueModel(name: 'Australia', value: 'Australia'),
  DropDownValueModel(name: 'Brazil', value: 'Brazil'),
  DropDownValueModel(name: 'Canada', value: 'Canada'),
  DropDownValueModel(name: 'China', value: 'China'),
  DropDownValueModel(name: 'Egypt', value: 'Egypt'),
  DropDownValueModel(name: 'France', value: 'France'),
  DropDownValueModel(name: 'Germany', value: 'Germany'),
  DropDownValueModel(name: 'India', value: 'India'),
  DropDownValueModel(name: 'Indonesia', value: 'Indonesia'),
  DropDownValueModel(name: 'Iraq', value: 'Iraq'),
  DropDownValueModel(name: 'Italy', value: 'Italy'),
  DropDownValueModel(name: 'Japan', value: 'Japan'),
  DropDownValueModel(name: 'Jordan', value: 'Jordan'),
  DropDownValueModel(name: 'Kuwait', value: 'Kuwait'),
  DropDownValueModel(name: 'Lebanon', value: 'Lebanon'),
  DropDownValueModel(name: 'Libya', value: 'Libya'),
  DropDownValueModel(name: 'Morocco', value: 'Morocco'),
  DropDownValueModel(name: 'Netherlands', value: 'Netherlands'),
  DropDownValueModel(name: 'Oman', value: 'Oman'),
  DropDownValueModel(name: 'Pakistan', value: 'Pakistan'),
  DropDownValueModel(name: 'Palestine', value: 'Palestine'),
  DropDownValueModel(name: 'Qatar', value: 'Qatar'),
  DropDownValueModel(name: 'Russia', value: 'Russia'),
  DropDownValueModel(name: 'Saudi Arabia', value: 'Saudi Arabia'),
  DropDownValueModel(name: 'South Africa', value: 'South Africa'),
  DropDownValueModel(name: 'Spain', value: 'Spain'),
  DropDownValueModel(name: 'Sudan', value: 'Sudan'),
  DropDownValueModel(name: 'Syria', value: 'Syria'),
  DropDownValueModel(name: 'Tunisia', value: 'Tunisia'),
  DropDownValueModel(name: 'Turkey', value: 'Turkey'),
  DropDownValueModel(name: 'United Arab Emirates', value: 'United Arab Emirates'),
  DropDownValueModel(name: 'United Kingdom', value: 'United Kingdom'),
  DropDownValueModel(name: 'United States', value: 'United States'),
  DropDownValueModel(name: 'Yemen', value: 'Yemen'),
];

